-- MySQL Script generated by MySQL Workbench
-- Fri Nov 13 21:51:56 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project` DEFAULT CHARACTER SET utf8 ;
USE `project` ;

-- -----------------------------------------------------
-- Table `project`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `user_email` VARCHAR(45) NOT NULL,
  `user_password` VARCHAR(128) NOT NULL,
  `user_role` ENUM("ADMIN", "USER") NOT NULL,
  `user_status` ENUM("BLOCKED", "ENABLE", "NOT_CONFIRMED") NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_surname` VARCHAR(45) NOT NULL,
  `user_patronymic` VARCHAR(45) NOT NULL,
  `user_balance` DOUBLE NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `order_creation_date` BIGINT(255) NOT NULL,
  `order_closing_date` BIGINT(255) NOT NULL,
  `order_status` ENUM("UNDER_CONSIDERATION", "DENIED", "PRODUCED") NOT NULL,
  `user_id_fk` INT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_users1_idx` (`user_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `project`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`images` (
  `image_id` INT NOT NULL AUTO_INCREMENT,
  `image_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`image_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`products` (
  `product_id` INT NOT NULL AUTO_INCREMENT,
  `product_title` VARCHAR(64) NOT NULL,
  `product_price` DOUBLE NOT NULL,
  `product_description` VARCHAR(1000) NOT NULL,
  `image_id_fk` INT NOT NULL,
  PRIMARY KEY (`product_id`),
  INDEX `fk_products_images1_idx` (`image_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_products_images1`
    FOREIGN KEY (`image_id_fk`)
    REFERENCES `project`.`images` (`image_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`order_item` (
  `order_item_id` INT NOT NULL AUTO_INCREMENT,
  `product_id_fk` INT NOT NULL,
  `order_id_fk` INT NOT NULL,
  PRIMARY KEY (`order_item_id`),
  INDEX `fk_order_item_products1_idx` (`product_id_fk` ASC) VISIBLE,
  INDEX `fk_order_item_orders1_idx` (`order_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_order_item_products1`
    FOREIGN KEY (`product_id_fk`)
    REFERENCES `project`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_item_orders1`
    FOREIGN KEY (`order_id_fk`)
    REFERENCES `project`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project`.`basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project`.`basket` (
  `basket_id` INT NOT NULL AUTO_INCREMENT,
  `user_id_fk` INT NOT NULL,
  `product_id_fk` INT NOT NULL,
  PRIMARY KEY (`basket_id`),
  INDEX `fk_basket_users1_idx` (`user_id_fk` ASC) VISIBLE,
  INDEX `fk_basket_products1_idx` (`product_id_fk` ASC) VISIBLE,
  CONSTRAINT `fk_basket_users1`
    FOREIGN KEY (`user_id_fk`)
    REFERENCES `project`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_basket_products1`
    FOREIGN KEY (`product_id_fk`)
    REFERENCES `project`.`products` (`product_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
